name: Unusuals
version: 0.2.0-SNAPSHOT
main: net.amigocraft.unusuals.Main
description: Unusual hats, in Minecraft!

commands:
  unusual:
    description: The main command for the plugin.
    usage: /unusual [args]
    
permissions:
  unusual.spawn:
    description: Allows spawning of unusuals.
    default: op